name = "raf-tracking"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
TRACKING_API_KEY = "6e117371f30799cce6ea7d873d59fc384476571cad02a8070b501ee5bccc60"
META_PIXEL_ID = "1074649728831383"
META_CAPI_TOKEN = "YOUR_META_CAPI_ACCESS_TOKEN"
TIKTOK_PIXEL_ID = "YOUR_TIKTOK_PIXEL_ID"
TIKTOK_EVENTS_TOKEN = "YOUR_TIKTOK_EVENTS_TOKEN"
